%%{init:{'theme':'dark','themeVariables':{'lineColor':'#FFA500'}}}%%
graph TD
    MET["<b>BRAIN METABOLISM</b><br/>Sections 13.1-13.3"]
    MET --> ENERGY["<b>Energy Demands</b><br/>2% body mass, 20% energy<br/>20% O2, 25% glucose<br/>15% cardiac output ~750mL/min<br/>~20 watts"]
    MET --> GLUC["<b>Glucose Metabolism</b>"]
    MET --> ALT["<b>Alternative Fuels</b>"]

    GLUC --> GLYC["Glycolysis in Astrocytes<br/>Glucose to Pyruvate 2 ATP"]
    GLUC --> OXPHOS["Oxidative Phosphorylation<br/>in Neurons ~30-32 ATP"]
    GLUC --> ANLS["Astrocyte-Neuron Lactate Shuttle<br/>Glutamate uptake triggers<br/>Astrocyte glycolysis to Lactate<br/>Lactate to Neuron oxidation"]

    ALT --> KETONE["Ketone Bodies<br/>60-70% energy in fasting<br/>Critical for neonates<br/>Therapeutic for epilepsy<br/>Investigated: AD, PD"]
    ALT --> LACT["Lactate from blood<br/>Exercise-induced<br/>Supports BDNF neuroplasticity"]