%%{init:{'theme':'dark','themeVariables':{'lineColor':'#FFD700'}}}%%
graph TD
    EM["<b>EMOTION: THEORIES & AMYGDALA</b><br/>Sections 9.1, 9.2"]

    EM --> TH["<b>Theories of Emotion</b>"]
    EM --> AMG["<b>Amygdala Processing Hub</b>"]

    TH --> JL["James-Lange 1884<br/>Stimulus-Body response-Emotion<br/>Facial feedback hypothesis"]
    TH --> CB["Cannon-Bard 1927<br/>Experience & Response simultaneous<br/>Both from thalamus"]
    TH --> SS["Schachter-Singer 1962<br/>Arousal + Cognitive label<br/>Context determines emotion"]
    TH --> CONST["Constructionist Barrett 2017<br/>Interoception + Conceptual category<br/>No 1:1 brain-emotion mapping"]

    AMG --> BLA["<b>Basolateral BLA</b><br/>All sensory inputs<br/>Assigns emotional valence<br/>Both aversive & appetitive"]
    AMG --> CEA["<b>Central CeA</b><br/>Primary output<br/>CeL: PKCd+ fear-off, SOM+ fear-on<br/>CeM to Hypothal, PAG, LC"]
    AMG --> BNST["<b>Extended Amygdala BNST</b><br/>Sustained anxiety<br/>Diffuse/unpredictable threats"]
    AMG --> BEYOND["<b>Beyond Fear</b><br/>BLA responds to rewards<br/>Projects to NAc<br/>= Relevance detector"]