%%{init:{'theme':'dark','themeVariables':{'lineColor':'#DA70D6'}}}%%
graph TD
    AS["<b>AUTONOMIC NS & SOCIAL NEUROSCIENCE</b><br/>Sections 9.7, 9.8"]

    AS --> ANS["<b>Autonomic NS</b>"]
    AS --> SOC["<b>Social Neuroscience</b>"]

    ANS --> SYMP["<b>Sympathetic Fight-Flight</b><br/>T1-L2 origin<br/>Pre: ACh nicotinic<br/>Post: NE adrenergic<br/>HR up, Bronchodilate, Pupils"]
    ANS --> PARA["<b>Parasympathetic Rest-Digest</b><br/>CN III,VII,IX,X + S2-S4<br/>Pre+Post: ACh<br/>Vagus X: 80% afferent<br/>Heart slow, GI motility"]
    ANS --> POLY["<b>Polyvagal Theory Porges</b><br/>1. Ventral vagal: Social engage<br/>2. Sympathetic: Mobilize<br/>3. Dorsal vagal: Freeze/Shutdown<br/>Influential but oversimplified"]

    SOC --> TOM["<b>Theory of Mind</b><br/>dmPFC: Self/other distinction<br/>TPJ: Perspective-taking<br/>pSTS: Social intent<br/>Overlaps with DMN"]
    SOC --> MIRROR["<b>Mirror Neuron System</b><br/>Premotor + Inf parietal + STS<br/>Action execution & observation<br/>Strong claims controversial"]
    SOC --> EMP["<b>Empathy</b>"]
    EMP --> AFFEMP["Affective Empathy<br/>Shared representations<br/>Anterior insula + ACC<br/>Psychopathy: Reduced"]
    EMP --> COGEMP["Cognitive Empathy<br/>Perspective-taking<br/>mPFC + TPJ<br/>Autism: Reduced"]