%%{init:{'theme':'dark','themeVariables':{'lineColor':'#FFD700','primaryColor':'#2c3e50','primaryTextColor':'#fff'}}}%%
graph TD
    BRAIN["<b>HUMAN BRAIN</b><br/>Section 1.1 - Gross Anatomy"]

    BRAIN --> PROS["<b>Prosencephalon</b><br/>Forebrain"]
    BRAIN --> MESEN["<b>Mesencephalon</b><br/>Midbrain"]
    BRAIN --> RHOMB["<b>Rhombencephalon</b><br/>Hindbrain"]

    PROS --> TEL["<b>Telencephalon</b><br/>Cerebral Hemispheres<br/>85% brain weight"]
    PROS --> DIEN["<b>Diencephalon</b><br/>Thalamus, Hypothalamus<br/>Epithalamus, Subthalamus"]

    TEL --> CC["Corpus Callosum<br/>200-300M axons<br/>Connects hemispheres"]
    TEL --> SURF["Cortical Surface<br/>Gyri & Sulci<br/>~2,500 cm2 area"]

    MESEN --> SC["Superior/Inferior Colliculi<br/>Visual & Auditory reflexes"]
    MESEN --> SN["Substantia Nigra<br/>Dopamine, Motor control"]
    MESEN --> VTA["VTA<br/>Reward signaling"]
    MESEN --> PAG["Periaqueductal Gray<br/>Pain modulation"]

    RHOMB --> META["<b>Metencephalon</b>"]
    RHOMB --> MYEL["<b>Myelencephalon</b><br/>Medulla Oblongata"]

    META --> PONS["Pons<br/>Cortex-Cerebellum relay<br/>CN V-VIII"]
    META --> CBLM["Cerebellum<br/>69B neurons, 50% of all<br/>Only 10% volume"]

    PONS --> LC["Locus Coeruleus<br/>Norepinephrine"]
    PONS --> RAPH["Raphe Nuclei<br/>Serotonin"]

    CBLM --> VEST["Vestibulocerebellum<br/>Balance & Eye movement"]
    CBLM --> SPIN["Spinocerebellum<br/>Limb & Trunk motor"]
    CBLM --> CERE["Cerebrocerebellum<br/>Motor planning, Cognition"]

    MYEL --> CARD["Cardiovascular Center<br/>Heart rate & BP"]
    MYEL --> RESP["Respiratory Center<br/>Breathing rhythm"]
    MYEL --> PYDEC["Pyramidal Decussation<br/>90% motor fibers cross"]