%%{init:{'theme':'dark','themeVariables':{'lineColor':'#FFD700'}}}%%
graph TD
    PRE["<b>PRENATAL BRAIN DEVELOPMENT</b><br/>Section 11.1"]

    PRE --> NT["<b>Neural Tube Wk 3-4</b><br/>Neural plate-Folds-Tube<br/>Anterior=Brain, Posterior=Spinal<br/>Defects: Anencephaly, Spina bifida<br/>Folate reduces 70%"]
    PRE --> PATT["<b>Patterning</b><br/>AP: Wnt/FGF/Retinoic acid<br/>DV: BMP dorsal, Shh ventral<br/>Hox genes: Rhombomere identity"]
    PRE --> PROLIF["<b>Proliferation Wk 5-25</b><br/>VZ + SVZ progenitors<br/>Outer radial glia = Human expansion<br/>Peak: 250K neurons/min"]
    PRE --> MIG["<b>Migration Wk 8-24</b><br/>Radial: Along glial fibers<br/>Inside-out: Deep first<br/>Tangential: Interneurons from GE<br/>Reelin stop signal"]
    PRE --> AXON["<b>Axon Guidance Wk 8-28</b><br/>Netrins: Attract/Repel midline<br/>Slits: Repulsive midline<br/>Semaphorins: Repulsive<br/>Ephrins: Topographic maps"]
    PRE --> SYNGEN["<b>Synaptogenesis</b><br/>Begins ~Wk 20, Explodes postnatal<br/>Peak 150% adult levels<br/>Visual 8mo, Auditory 3mo<br/>PFC 3.5 years"]