%%{init:{'theme':'dark','themeVariables':{'lineColor':'#FFD700'}}}%%
graph TD
    AD["<b>ALZHEIMER'S DISEASE</b><br/>Section 15.2 | Most common neurodegeneration"]
    AD --> AMYL["<b>Amyloid Plaques</b><br/>APP-BACE1-gamma secretase-Abeta<br/>Oligomers most toxic<br/>DMN distribution first<br/>PET: PiB, Florbetapir"]
    AD --> TAU["<b>Neurofibrillary Tangles</b><br/>Hyperphosphorylated tau<br/>Braak staging I-VI<br/>Transentorhinal-Limbic-Neocortex<br/>Tau correlates better with decline"]
    AD --> SYNLOSS["<b>Synaptic Loss</b><br/>Strongest cognitive correlate<br/>Complement C1q-C3-CR3"]
    AD --> CHOL["<b>Cholinergic Degeneration</b><br/>Nucleus basalis loss<br/>AChE inhibitors: Symptomatic"]
    AD --> GEN["<b>Genetics</b>"]
    GEN --> EARLY["Early-onset less than 5%:<br/>APP, PSEN1, PSEN2<br/>Down syndrome: 3x APP"]
    GEN --> LATE["Late-onset >95%:<br/>APOE e4: 3-12x risk<br/>TREM2: Microglial phago<br/>75+ GWAS loci"]
    AD --> TX["<b>Therapy 2025</b><br/>Lecanemab, Donanemab<br/>25-35% slowing decline<br/>ARIA side effects"]