%%{init:{'theme':'dark','themeVariables':{'lineColor':'#00BFFF'}}}%%
graph TD
    NP["<b>NEUROPEPTIDES & OTHER TRANSMITTERS</b><br/>Sections 4.5, 4.6, 4.7"]

    NP --> OPIOID["<b>Opioid Peptides</b><br/>Endorphins, Enkephalins, Dynorphins<br/>mu=reward, delta, kappa=dysphoria<br/>All Gi/Go: reduce cAMP, open K+"]
    NP --> ECANN["<b>Endocannabinoids</b><br/>Anandamide, 2-AG<br/>Retrograde messengers<br/>CB1 Gi: depress release<br/>DSE/DSI plasticity"]
    NP --> OREX["<b>Orexin/Hypocretin</b><br/>~70K lateral hypo neurons<br/>Wakefulness stabilizer<br/>Loss = Narcolepsy Type 1<br/>Suvorexant = sleep aid"]
    NP --> OXVP["<b>Oxytocin & Vasopressin</b><br/>PVN & Supraoptic<br/>OT: Bonding, Trust, Maternal<br/>VP: Water, Vasoconstriction<br/>Social behavior"]
    NP --> NPY["<b>NPY</b><br/>Most abundant peptide<br/>Appetite Y1/Y5, Anxiolytic<br/>Co-released GABA & NE"]

    NP --> OTHER["<b>Other Systems</b>"]
    OTHER --> HIST["Histamine - TMN<br/>H1 Gq wakefulness<br/>H3 Gi autoreceptor<br/>Antihistamines = sedation"]
    OTHER --> PURINE["Purines<br/>ATP: P2X ion, P2Y GPCR<br/>Adenosine: A1 inhibitory<br/>A2A excitatory striatum<br/>Caffeine = A1/A2A antagonist"]
    OTHER --> GAS["Gaseous Transmitters<br/>NO: nNOS, retrograde LTP<br/>CO: HO-2, neuromodulator<br/>H2S: Enhances NMDA"]

    NP --> COTRANS["<b>Co-Transmission</b><br/>Most neurons release multiple NTs<br/>GABAergic subtypes: PV+, SST+, VIP+<br/>VTA DA co-releases Glutamate<br/>Different firing rates = different signals"]