%%{init:{'theme':'dark','themeVariables':{'lineColor':'#FFD700'}}}%%
graph TD
    BBB["<b>BLOOD-BRAIN BARRIER & HP AXES</b><br/>Sections 12.1, 12.2"]
    BBB --> STRUCT["<b>BBB Structure</b><br/>Endothelial tight junctions<br/>Pericytes, Astrocyte endfeet 99%<br/>50-100x tighter than peripheral"]
    BBB --> TRANS["<b>Transport</b><br/>Passive: O2, CO2, Ethanol<br/>Carrier: GLUT1 glucose, LAT1 AA<br/>Receptor: Transferrin, LRP1<br/>Efflux: P-gp pumps drugs out"]
    BBB --> CVO["<b>No BBB Regions</b><br/>Area postrema: Emesis<br/>Median eminence: Hormones<br/>SFO/OVLT: Osmolality<br/>Pineal: Melatonin"]
    BBB --> ANT["<b>Anterior Pituitary Axes</b><br/>CRH-ACTH-Cortisol HPA<br/>GnRH-FSH/LH-Sex steroids HPG<br/>TRH-TSH-T3/T4 HPT<br/>GHRH-GH-IGF1<br/>DA inhibits Prolactin"]
    BBB --> POST_P["<b>Posterior Pituitary</b><br/>Oxytocin: Social bonding<br/>Labor, Milk, Trust<br/>Vasopressin ADH: Water<br/>Vasoconstriction, Pair bonding"]