%%{init:{'theme':'dark','themeVariables':{'lineColor':'#00FF7F'}}}%%
graph TD
    SF["<b>SLEEP FUNCTIONS & DISORDERS</b><br/>Sections 14.5, 14.6"]
    SF --> FUNC["<b>Functions of Sleep</b>"]
    SF --> DIS["<b>Sleep Disorders</b>"]

    FUNC --> MEMCON["Memory Consolidation<br/>NREM: Declarative hippo-cortical<br/>REM: Procedural, Emotional, Creative"]
    FUNC --> SHY["Synaptic Homeostasis SHY<br/>Wake: Net potentiation<br/>Sleep: Global downscaling<br/>Renewed capacity, Better SNR"]
    FUNC --> IMMUNE["Immune: NREM pro-inflammatory<br/>Deprivation: 4.2x cold risk<br/>Reduced NK activity"]
    FUNC --> EMREG["Emotional Regulation<br/>REM recalibrates amygdala<br/>Deprivation: 60% more reactive"]

    DIS --> INSOM["Insomnia ~10%<br/>Hyperarousal model<br/>CBT-I first-line"]
    DIS --> OSA["OSA 10-30%<br/>Cognitive impairment<br/>CV disease, Neuro risk<br/>CPAP treatment"]
    DIS --> NARC["Narcolepsy Type 1<br/>Loss of orexin neurons<br/>Autoimmune HLA-DQB1<br/>CSF orexin-A less than 110pg/mL"]
    DIS --> RBD["RBD: Loss REM atonia<br/>80%+ develop alpha-synucleinopathy<br/>PD/DLB/MSA in 10-15 years<br/>Strongest prodromal marker"]